# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8166ed5cd9bbe2927977f5f9c726707047dfeeacd9cd1dd4e61e73114319c8f1ac9b2febf1003cd5d07f026725da25ed58354b2c93318ddc4fb078309a4b1d9d

test:
  secret_key_base: 702e1c6f339d4d04f13309cb0c2dfc8fd28a359ca89638228ea3313ab8ae4af6bd91d9200bc2b017b2ad77651309d81cbbd868ea96235237341ad7f324fd3ee9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
